# Mlima Connect - Render.com Configuration
# This file defines the infrastructure for your Mlima Connect application

# List of services to deploy
services:
  - type: web
    name: mlima-connect
    env: node
    plan: free
    region: oregon  # Options: oregon, ohio, frankfurt, singapore, sydney
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    envVarFiles:
      - .env  # For local development secrets (not committed to git)
    
    # Auto-deploy settings
    autoDeploy: true
    branch: master
    
    # Health check path
    healthCheckPath: /
    
    # Uncomment and add these when you set up a database
    # database:
    #   name: mlima_db
    #   databaseName: mlima_production
    #   user: mlima_user
    #   plan: free  # free, starter, standard, or pro
    
    # Uncomment to add a custom domain
    # customDomains:
    #   - name: yourdomain.com
    #     domain: yourdomain.com
    #     type: apex
    #   - name: www.yourdomain.com
    #     domain: www.yourdomain.com
    #     type: www
