databases:
  - name: mlima-connect-db
    databaseName: mlima_connect_db # You can name your DB this
    user: mlima_user
    plan: free # Use the free tier for development

services:
  - type: web
    name: mlima-connect-app
    rootDir: .
    runtime: node
    # Specify the Node.js version to ensure compatibility
    node:
      version: "20"
    plan: free # Use the free tier for development
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mlima-connect-db
          property: connectionString
      - key: NODE_ENV
        value: production
