# Render Configuration File
# This file defines the infrastructure for your Mlima Connect static website

services:
  - type: web
    name: mlima-connect
    env: static
    plan: free
    branch: master
    autoDeploy: true
    buildCommand: ""
    staticPublishPath: "."
    envVars:
      - key: NODE_VERSION
        value: 16.14.0
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    healthCheckPath: /index.html
