# Render Configuration File
# This file defines the infrastructure for your Mlima Connect static website

# List of services to deploy
services:
  - type: web
    name: mlima-connect
    env: static
    region: oregon  # Options: oregon, ohio, frankfurt, singapore, sydney
    plan: free
    branch: master
    autoDeploy: true
    
    # Static site configuration
    static:
      publish: .
      buildCommand: ""
      
    # Routes for client-side routing
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    
    # Health check
    healthCheckPath: /index.html
    
    # Environment variables
    envVars:
      - key: NODE_VERSION
        value: 16.14.0
