# Mlima Connect Static Site Configuration
services:
  - type: web
    name: mlima-connect
    env: static
    buildCommand: ""
    staticPublishPath: "."
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
