# Minimal configuration for Mlima Connect static site
services:
  - type: static_site
    name: mlima-connect
    env: static
    buildCommand: ""
    staticPublishPath: "."
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
